// New Fazenda

POST http://localhost:8080/fazenda/create
content-type: application/json
    
    {
        "nome": "Santos",
        "proprietario": "Pedro Pascal",
        "area": 20,
        "image": "https://imagem_fazenda"
    }

###

// Get All Fazendas

GET http://localhost:8080/fazenda/all
content-type: application/json

###

// Get One Fazenda by Name

GET http://localhost:8080/fazenda/find/Santos
content-type: application/json

###

// Update Fazenda

PUT http://localhost:8080/fazenda/edit/Santos
content-type: application/json

    {
        "nome": "Santos",
        "area": 30,
        "proprietario": "Pedro Pascal"
    }

###

// Delete Fazenda

DELETE http://localhost:8080/fazenda/delete/Alos
content-type: application/json